text_analyzer/urls.py
from home import views as home_views
from django.urls import path

urlpatterns = [
    path('', home_views.HomeView.as_view(), name='home'),
    path('upload', home_views.upload_file, name='upload'),
    path('archive', home_views.ArchiveView.as_view(), name='archive'),
    path('<int:pk>/results', home_views.ResultsView.as_view(), name='results'),
    path('<int:record_id>/plot', home_views.generate_histogram, name='plot')
]

home/models.py
from codecs import iterdecode
import csv
from io import BytesIO
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from textblob import TextBlob
from django.db import models
from django.core.exceptions import ValidationError

def validate_file_contents(file):
    '''
    Verify input file format: 
    - must be English language
    - must be at least 10 words
    '''
    file.seek(0)
    text = TextBlob(file.read().decode('utf-8'))
    if len(text.words) < 10:
        raise ValidationError('Document is too short')
    lang = text.detect_language() 
    if lang != 'en':
        raise ValidationError(f'Unsupported language: {lang}')

class Record(models.Model):
    # Provided by the user.
    description = models.CharField(max_length=255)
    # Original file is stored for future re-processing.
    datafile = models.FileField(upload_to='uploads/', validators=[validate_file_contents])
    uploaded_at = models.DateTimeField(auto_now_add=True)
    processed_at = models.DateTimeField()
    # Provided by the user.
    user_name = models.CharField(max_length=255)
    # Fields below are derived from datafile and are stored in the DB for performance reasons.
    # Range [-1, 1].
    polarity = models.FloatField()
    # Range [0, 1].
    subjectivity = models.FloatField()

    def __str__(self):
        return self.description

    def polarity_text(self):
        if self.polarity < -0.5:
            return "very negative"
        if self.polarity < 0:
            return "somewhat negative"
        if self.polarity < 0.5:
            return "somewhat positive"
        return "very positive"

    def subjectivity_text(self):
        if self.subjectivity < 0.3:
            return "very objective"
        if self.subjectivity < 0.7:
            return "neither subjective nor objective"
        return "very subjective"

    def histogram(self):
        '''
        Visualize text's polarity compared to all other samples in the system. 
        Returns a PNG image.
        '''  
        # Using hardcoded made-up numbers for testing. For production this should be based on actual data.
        weight = [9, 19, 38, 69, 119, 192, 288, 406, 536, 663, 768, 833, 847, 806, 719, 601, 471, 345, 237, 153, 92, 52, 27, 13]
        num_buckets = len(weight)
        buckets = np.linspace(-1 + 1. / num_buckets, 1 - 1. / num_buckets, num_buckets)

        def selected(bucket):
            return bucket - 1. / num_buckets <= self.polarity < bucket + 1. / num_buckets
        colors = ['red' if selected(bucket) else 'dodgerblue' for bucket in buckets]

        matplotlib.use('Agg')
        plt.bar(buckets, weight, 2. / num_buckets, color=colors)
        # Axes and labels.
        plt.xticks(np.linspace(-1, 1, 10))
        plt.yticks([])
        plt.tight_layout()

        # Write image to output string.
        buffer = BytesIO()
        plt.savefig(buffer, format='png')
        return buffer.getvalue()

home/forms.py
from django import forms
from .models import Record

class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ('description', 'user_name', 'datafile')

home/views.py
from codecs import iterdecode
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views.generic import View, ListView, DetailView
from textblob import TextBlob
from .forms import RecordForm
from .models import Record

class HomeView(View):
    def get(self, request):
        return render(request, 'home.html')

class ArchiveView(ListView):
    model = Record
    template_name = 'archive.html'

class ResultsView(DetailView):
    model = Record
    template_name = 'results.html'

def upload_file(request):
    if request.method == 'POST':
        form = RecordForm(request.POST, request.FILES)
        if form.is_valid():
            record = form.save(commit=False)
            # Precompute a bunch of data and save it to the database, since it could be slow 
            # in the real system and we don't want to redo it each time we display results to the user.
            record.datafile.seek(0)
            text = TextBlob(record.datafile.read().decode('utf-8'))
            record.polarity = text.polarity
            record.subjectivity = text.subjectivity
            record.processed_at = timezone.now()
            record.save()
            return HttpResponseRedirect(reverse('results', args=(record.id,)))
    else:
        form = RecordForm()
    context = {'form': form}
    return render(request, 'upload_file.html', context)

def generate_histogram(request, record_id):
    record = get_object_or_404(Record, pk=record_id)
    return HttpResponse(record.histogram(), content_type='image/png')

templates/archive.html
{% extends 'base.html' %}

{% block content %}
{% load tz %}
<script type="text/javascript">$(document).ready(function () { $("#dataTable").DataTable(); });</script>
<div width="100%">
	<p><a href="{% url 'home' %}"><i class="fas fa-home"></i> Return to home</a></p>
{% if record_list %}  
    <table id="dataTable" class="table table-striped table-bordered table-sm text-center" cellspacing="0">
    <thead>
    	<th class="th-sm align-middle">Description</th>
    	<th class="th-sm align-middle">Uploaded on</th>
    	<th class="th-sm align-middle">By user</th>
    	<th class="th-sm align-middle">Processed on</th>
    	<th class="th-sm align-middle">Text polarity</th>
    	<th class="th-sm align-middle">Text subjectivity</th>
  	</thead>
  	<tbody>
    {% for record in record_list %}
	<tr>
		<td><a href="{% url 'results' record.id %}">{{ record.description }}</a></td>
		<td>{{ record.uploaded_at|timezone:"America/Los_Angeles" }}</td>
		<td>{{ record.user_name }}</td>
		<td>{{ record.processed_at|timezone:"America/Los_Angeles" }}</td>
		<td>{{ record.polarity|floatformat:2 }}</td>
		<td>{{ record.subjectivity|floatformat:2 }}</td>
	</tr>
    {% endfor %}
    <tbody>
    </table>
{% else %}
    <p>No files are uploaded yet.</p>
{% endif %}
 </div>
{% endblock %}

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Text analysis</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css"/>
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.js"></script>
</head>
<body style="margin:50px 25px;">
    {% block content %}
    {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1 style="text-align:center;">Welcome to the Text-a-lyzer!</h1>
<p style="text-align:center;"><a href="{% url 'upload' %}"><i class="fas fa-upload"></i> Upload a new text file</a></p>
<p style="text-align:center;"><a href="{% url 'archive' %}"><i class="fas fa-envelope-open-text"></i> See previously uploaded files</a></p>
{% endblock %}

templates/results.html
{% extends 'base.html' %}

{% block content %}
{% load tz %}
<p><a href="{% url 'archive' %}"><i class="fas fa-envelope-open-text"></i> Return to all documents</a></p>
<p>Your document is {{ record.polarity_text }} and {{ record.subjectivity_text }}.</p>
<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#more">See more...</button>
<div id="more" class="collapse">
  Document description: {{ record.description }} as file number: {{ record.id }}<br/>
  Polarity score (from -1 to 1): {{ record.polarity|floatformat:2 }}<br/>
  Subjectivity score (from 0 to 1): {{ record.subjectivity|floatformat:2 }}<br/>
  Uploaded on: {{ record.uploaded_at|timezone:"America/Los_Angeles" }} by {{ record.user_name }}<br/>
  Processed on: {{ record.processed_at|timezone:"America/Los_Angeles" }}<br/>
</div>
<p><br/>Here is how you compare to the rest of the internet:<br/><img src="{% url 'plot' record.id %}"></img></p>
{% endblock %}

templates/upload_file.html
{% extends 'base.html' %}

{% block content %}
<p><a href="{% url 'home' %}"><i class="fas fa-home"></i> Return to home</a></p>
<style>th { padding: 0.5em; } .errorlist {color: #f44268;} </style>
<div class="card text-white bg-primary mx-auto" style="max-width: 24rem;">
  <div class="card-header">Upload your text sample here:</div>
  <div class="card-body">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
    	  {{ form.as_table }}
      </table>
      <button type="submit">Upload</button>
    </form>
  </div>
</div>
{% endblock %}